(defvar root-dir (file-name-directory (or (buffer-file-name) load-file-name)))
(defvar customac-dir (expand-file-name "customac" root-dir))
(add-to-list 'load-path customac-dir)

(require 'customac-packages)
(require 'customac-editor)
(require 'customac-popwin)
(require 'customac-ido)
(require 'customac-auto-complete)
(require 'customac-clojure)
(require 'customac-magit)
(require 'customac-windowing)
(require 'customac-theming)
(require 'customac-erc)
(require 'customac-bindings)
(require 'customac-evil)

;; enforce loading this *only* if using osx
(when (string= system-type "darwin")
  (require 'customac-osx))
